2025-07-07 15:07:28 | INFO     | __main__:get_account:56 - 收到的exchange参数: %s
2025-07-07 15:07:28 | INFO     | __main__:get_account:58 - ex实例类型: %s
2025-07-07 15:07:28 | INFO     | __main__:get_account:60 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-07 15:07:28 | INFO     | __main__:get_account:61 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-07 15:07:28 | ERROR    | __main__:get_account:95 - 接口异常: %s
Traceback (most recent call last):

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
           │       └ (<gevent._socket3.socket at 0x107ba7dc0 object, fd=21, family=2, type=1, proto=0>, ('127.0.0.1', 62232))
           └ <bound method WSGIServer.handle of <WSGIServer at 0x107a59410 fileno=19 address=0.0.0.0:5001>>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/gevent/pywsgi.py", line 1704, in handle
    handler.handle()
    │       └ <function WSGIHandler.handle at 0x107f207c0>
    └ <gevent.pywsgi.WSGIHandler object at 0x107f33a50>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/gevent/pywsgi.py", line 578, in handle
    result = self.handle_one_request()
             │    └ <function WSGIHandler.handle_one_request at 0x107f20ae0>
             └ <gevent.pywsgi.WSGIHandler object at 0x107f33a50>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/gevent/pywsgi.py", line 808, in handle_one_request
    self.handle_one_response()
    │    └ <function WSGIHandler.handle_one_response at 0x107f21260>
    └ <gevent.pywsgi.WSGIHandler object at 0x107f33a50>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/gevent/pywsgi.py", line 1111, in handle_one_response
    self.run_application()
    │    └ <function WSGIHandler.run_application at 0x107f211c0>
    └ <gevent.pywsgi.WSGIHandler object at 0x107f33a50>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/gevent/pywsgi.py", line 1058, in run_application
    self.process_result()
    │    └ <function WSGIHandler.process_result at 0x107f21120>
    └ <gevent.pywsgi.WSGIHandler object at 0x107f33a50>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/gevent/pywsgi.py", line 1042, in process_result
    for data in self.result:
                │    └ <generator object DebuggedApplication.debug_application at 0x107df7100>
                └ <gevent.pywsgi.WSGIHandler object at 0x107f33a50>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <bound method WSGIHandler.start_response of <gevent.pywsgi.WSGIHandler object at 0x107f33a50>>
               │    │   └ {'GATEWAY_INTERFACE': 'CGI/1.1', 'SERVER_SOFTWARE': 'gevent/20.0 Python/3.11', 'SCRIPT_NAME': '', 'wsgi.version': (1, 0), 'ws...
               │    └ <bound method Flask.wsgi_app of <Flask 'web_app'>>
               └ <werkzeug.debug.DebuggedApplication object at 0x107eb8ed0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x10427c9a0>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x10427c900>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (HEAD, GET, OPTIONS) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x107dad940>, 'index': <function index at 0x107e84f40>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x10427cb80>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 77, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1046cfba0>
              └ <exchanges.aster.Aster object at 0x106fcfc90>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 617, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x1046cf380>
               └ <exchanges.aster.Aster object at 0x106fcfc90>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 425, in _signed_request
    response = requests.get(url, params=params, headers=headers)
               │        │   │           │               └ {'X-MBX-APIKEY': '2edb2ff9f6e793b8367b48c7fbfbf57fef0114e872f725e6e643bbc0f21869e3'}
               │        │   │           └ {'timestamp': 1751872048705, 'recvWindow': 5000, 'signature': '861c6f8a3384f45566dfc79b5350a07e774a4df2427204be5d7e7b5e2939d9...
               │        │   └ 'https://fapi.asterdex.com/fapi/v2/account'
               │        └ <function get at 0x10468a520>
               └ <module 'requests' from '/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/requests/__init__.py'>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           │              │           │         └ {'headers': {'X-MBX-APIKEY': '2edb2ff9f6e793b8367b48c7fbfbf57fef0114e872f725e6e643bbc0f21869e3'}}
           │              │           └ {'timestamp': 1751872048705, 'recvWindow': 5000, 'signature': '861c6f8a3384f45566dfc79b5350a07e774a4df2427204be5d7e7b5e2939d9...
           │              └ 'https://fapi.asterdex.com/fapi/v2/account'
           └ <function request at 0x10468a3e0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': {'timestamp': 1751872048705, 'recvWindow': 5000, 'signature': '861c6f8a3384f45566dfc79b5350a07e774a4df2427204be5d7...
           │       │              │           └ 'https://fapi.asterdex.com/fapi/v2/account'
           │       │              └ 'get'
           │       └ <function Session.request at 0x1046cc360>
           └ <requests.sessions.Session object at 0x107f3a950>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': None, 'allow_redirects': True, 'proxies': OrderedDict([('http', 'http://127.0.0.1:1087'), ('https', 'http://127.0...
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x1046cc860>
           └ <requests.sessions.Session object at 0x107f3a950>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'timeout': None, 'proxies': OrderedDict([('http', 'http://127.0.0.1:1087'), ('https', 'http://127.0.0.1:1087')]), 'stream': ...
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x1046bbba0>
        └ <requests.adapters.HTTPAdapter object at 0x107fe88d0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x1044fb880>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x107d84c10>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 773, in urlopen
    self._prepare_proxy(conn)
    │    │              └ None
    │    └ <function HTTPSConnectionPool._prepare_proxy at 0x1044fbb00>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x107d84c10>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _prepare_proxy
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x1044c37e0>
    └ <urllib3.connection.HTTPSConnection object at 0x107fe8850>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/urllib3/connection.py", line 790, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        └ <function _ssl_wrap_socket_and_match_hostname at 0x1044c1c60>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.11/site-packages/urllib3/connection.py", line 931, in _ssl_wrap_socket_and_match_hostname
    context.verify_mode = resolve_cert_reqs(cert_reqs)
    │       │             │                 └ 'CERT_REQUIRED'
    │       │             └ <function resolve_cert_reqs at 0x10442ad40>
    │       └ <property object at 0x1035363e0>
    └ <ssl.SSLContext object at 0x104517f50>

  File "/opt/homebrew/Cellar/python@3.11/3.11.12_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 742, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
          │           │                               │     └ <VerifyMode.CERT_REQUIRED: 2>
          │           │                               └ <ssl.SSLContext object at 0x104517f50>
          │           └ <class 'gevent.ssl.SSLContext'>
          └ <class 'gevent.ssl.SSLContext'>

  File "/opt/homebrew/Cellar/python@3.11/3.11.12_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 742, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
          │           │                               │     └ <VerifyMode.CERT_REQUIRED: 2>
          │           │                               └ <ssl.SSLContext object at 0x104517f50>
          │           └ <class 'gevent.ssl.SSLContext'>
          └ <class 'gevent.ssl.SSLContext'>

  File "/opt/homebrew/Cellar/python@3.11/3.11.12_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 742, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
          │           │                               │     └ <VerifyMode.CERT_REQUIRED: 2>
          │           │                               └ <ssl.SSLContext object at 0x104517f50>
          │           └ <class 'gevent.ssl.SSLContext'>
          └ <class 'gevent.ssl.SSLContext'>
  [Previous line repeated 482 more times]

RecursionError: maximum recursion depth exceeded while calling a Python object
